### ISSUE TITLE
Board of Trustees Level on Join

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#45]
**@elisegranata said:**

> Is it possible to include an extra $1500 "Board of Trustees Level" on the join.santacruzmah.org page This is for board members to pay their dues, so there's no benefit language necessary. 

> Folks won't necessarily already be in the system, so it would be great to put it in both New and Renew.

**Comment by halfempty** [comment]
@elisegranata Okay, please take a look at these:

http://join.santacruzmah.org/new/new-board-of-trustees/
http://join.santacruzmah.org/renew/renew-board-of-trustees/

These run the same infrastructure as the "Circle Level" memberships, so should behave exactly the same as those, but with a new title and dollar amount.

It would be ideal if you have something like a testing paypal account that you could use to actually complete the transactions. If that's a problem 'cause of the high dollar amount, we could drop it down to $1.50 or something for testing, then bring it back up before linking them up.

**Comment by elisegranata** [comment]
Yes, could you drop the amount down please to test?

Thanks!

Elise

On Thu, May 14, 2015 at 11:47 AM, Marty Spellerberg <
notifications@github.com> wrote:

> @elisegranata <https://github.com/elisegranata> Okay, please take a look
> at these:
>
> http://join.santacruzmah.org/new/new-board-of-trustees/
> http://join.santacruzmah.org/renew/renew-board-of-trustees/
>
> These run the same infrastructure as the "Circle Level" memberships, so
> should behave exactly the same as those, but with a new title and dollar
> amount.
>
> It would be ideal if you have something like a testing paypal account that
> you could use to actually complete the transactions. If that's a problem
> 'cause of the high dollar amount, we could drop it down to $1.50 or
> something for testing, then bring it back up before linking them up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/45#issuecomment-102132969>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
3rd Friday: Beyond Borders (May 15th
<http://www.santacruzmah.org/event/3rd-friday-beyond-borders/>)
Memorial Day Remembrance (May 25th
<http://www.santacruzmah.org/event/memorial-day-remembrance/>)
FREE First Friday (June 5th
<http://www.santacruzmah.org/event/free-first-friday-25/>)

**Comment by halfempty** [comment]
@elisegranata Okay, dropped!

**Comment by elisegranata** [comment]
Did you both get notifications about a 'renewed' trustee membership and
'new' trustee membership?

Elise

On Thu, May 14, 2015 at 1:14 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> Okay, dropped!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/45#issuecomment-102154034>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
3rd Friday: Beyond Borders (May 15th
<http://www.santacruzmah.org/event/3rd-friday-beyond-borders/>)
Memorial Day Remembrance (May 25th
<http://www.santacruzmah.org/event/memorial-day-remembrance/>)
FREE First Friday (June 5th
<http://www.santacruzmah.org/event/free-first-friday-25/>)

**Comment by halfempty** [comment]
I personally don't get the notifications. They go to membership@santacruzmah.org

**Comment by halfempty** [comment]
@elisegranata I personally don't get the notifications. They go to membership@santacruzmah.org

**Comment by elisegranata** [comment]
Yep – I got both.



______________________________

*Lis DuBois*

Administrative Manager

Santa Cruz Museum of Art & History

705 Front St, Santa Cruz, CA 95060

831-429-1964 x7023

*http://www.santacruzmah.org/ <http://www.santacruzmah.org/>*



*From:* Elise Granata [mailto:elise@santacruzmah.org]
*Sent:* Thursday, May 14, 2015 1:19 PM
*To:* santacruzmah/santacruzmah
*Cc:* santacruzmah/santacruzmah; Karen Bush; Lis DuBois
*Subject:* Re: [santacruzmah] Board of Trustees Level on Join (#45)



Did you both get notifications about a 'renewed' trustee membership and
'new' trustee membership?


Elise



On Thu, May 14, 2015 at 1:14 PM, Marty Spellerberg <notifications@github.com>
wrote:

@elisegranata <https://github.com/elisegranata> Okay, dropped!

—
Reply to this email directly or view it on GitHub
<https://github.com/santacruzmah/santacruzmah/issues/45#issuecomment-102154034>
.





-- 

Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.



*Elise Granata*

*Marketing & Engagement Coordinator*

*Santa Cruz Museum of Art & History*

*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*

Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.


*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)



*Get to the MAH this month. *
*Here's what's coming up:*

3rd Friday: Beyond Borders (May 15th
<http://www.santacruzmah.org/event/3rd-friday-beyond-borders/>)

Memorial Day Remembrance (May 25th
<http://www.santacruzmah.org/event/memorial-day-remembrance/>)

FREE First Friday (June 5th
<http://www.santacruzmah.org/event/free-first-friday-25/>)

**Comment by halfempty** [comment]
@elisegranata Cool, so do you think the pages are good to go (re-up the dollar amounts and link from the homepage)?

**Comment by elisegranata** [comment]
Yep-- just waiting on a response from Karen, but I think we are good to go.
Thanks Marty!

Elise

On Thu, May 14, 2015 at 2:28 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> Cool, so do you think the
> pages are good to go (re-up the dollar amounts and link from the homepage)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/45#issuecomment-102175890>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
3rd Friday: Beyond Borders (May 15th
<http://www.santacruzmah.org/event/3rd-friday-beyond-borders/>)
Memorial Day Remembrance (May 25th
<http://www.santacruzmah.org/event/memorial-day-remembrance/>)
FREE First Friday (June 5th
<http://www.santacruzmah.org/event/free-first-friday-25/>)

**Comment by halfempty** [comment]
@elisegranata Okay, done!
