### ISSUE TITLE
Responsive: Calendar

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#47]
@elisegranata When it comes to responsive, the Event "Calendar" view is a big item. It's possible to convert it to responsive, but not a snap of the fingers. I'm referring to the template for pages such as this:

http://www.santacruzmah.org/events/month/

One factor is that we're using an older version of the plugin, which we've talked for sometime about updating to the latest. This update will mean revising our templates. A few possibilities:

1. We could update the plugin to the latest version, revise our templates for it, and at the same time convert them to responsive. This kills two birds with one stone, but is the most amount of work, and takes our focus off responsive, somewhat.

2. We could worry about the update another day, and just convert the current version to responsive. This keeps is focused, but means we'll have to re-do some work when we do tackle the update.

3. We could dodge the whole thing by dropping these screens from our site. I raise this possibility because of Joe's report that these pages are infrequently used, at least relative to their "List" counterparts.

At this moment I'm inclined towards option 3, but it's definitely something we should discuss.

**Comment by elisegranata** [comment]
Hey Marty,

Thank you for laying this out so clearly. I am also inclined towards option
3. Fortunately, these are decisions we now get to feel *super *great about
now that we have some actual data behind them, thanks to Joe's hard work.
Let's let that information save us the extra work and swerving focus that
would come if we went with #1 or #2. Cool?

Elise

On Wed, Jun 17, 2015 at 11:40 AM, Marty Spellerberg <
notifications@github.com> wrote:

> @elisegranata <https://github.com/elisegranata> When it comes to
> responsive, the Event "Calendar" view is a big item. It's possible to
> convert it to responsive, but not a snap of the fingers. I'm referring to
> the template for pages such as this:
>
> http://www.santacruzmah.org/events/month/
>
> One factor is that we're using an older version of the plugin, which we've
> talked for sometime about updating to the latest. This update will mean
> revising our templates. A few possibilities:
>
>    1.
>
>    We could update the plugin to the latest version, revise our templates
>    for it, and at the same time convert them to responsive. This kills two
>    birds with one stone, but is the most amount of work, and takes our focus
>    off responsive, somewhat.
>    2.
>
>    We could worry about the update another day, and just convert the
>    current version to responsive. This keeps is focused, but means we'll have
>    to re-do some work when we do tackle the update.
>    3.
>
>    We could dodge the whole thing by dropping these screens from our
>    site. I raise this possibility because of Joe's report that these pages are
>    infrequently used, at least relative to their "List" counterparts.
>
> At this moment I'm inclined towards option 3, but it's definitely
> something we should discuss.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/47>.
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
3rd Friday: Counter Culture (June 19th
<http://www.santacruzmah.org/event/3rd-friday-counter-culture/>)
Free First Friday: Princes of Surf Exhibition Opening (July 3rd
<http://www.santacruzmah.org/event/free-first-friday-26/>)
Yoga, Recess, and more events in Abbott Square - www.abbottsquare.org/events

**Comment by halfempty** [comment]
Okay, I've removed the links to "Calendar"
