### ISSUE TITLE
Create MailChimp action button

### ISSUE THREAD

**Issue by elisegranata** [santacruzmah/santacruzmah#51]
Create "Yes, I'm interested! Send me one e-mail the week of the event." button prompt for visitors to indicate interest in website events.

**Comment by elisegranata** [comment]
Okay, I created an embedded sign-up form here: http://www.santacruzmah.org/event/winterpalooza-2/

I am very excited about it, because I figured out how to add subscribers to pre-selected groups without showing the checkboxes in the form. Whenever someone subscribes, they are automatically added to a Winterpalooza segment! Boom! I need to style this more (or you can), but yes.

Would it make more sense for us to create an additional, more natural action like 'Add to my Google Calendar'?

**Comment by halfempty** [comment]
Styled it:

![image](https://cloud.githubusercontent.com/assets/775543/11670631/b14a516a-9dc8-11e5-9df9-e6c06c1598dc.png)

One aspect that's not perfect is it doesn't indicate anything has happened upon submit. So it's confusing. I'll research that.

**Comment by elisegranata** [comment]
That isn't great. But they do get a confirmation e-mail right away. PS THIS
LOOKS AMAZING!

On Tue, Dec 8, 2015 at 2:28 PM, Marty Spellerberg <notifications@github.com>
wrote:

> Styled it:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/775543/11670631/b14a516a-9dc8-11e5-9df9-e6c06c1598dc.png>
>
> One aspect that's not perfect is it doesn't indicate anything has happened
> upon submit. So it's confusing. I'll research that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/51#issuecomment-163038612>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
FREE First Friday: Wild Mushrooms & Functional Fungi Opening (Dec 4th)
<http://www.santacruzmah.org/event/free-first-friday-31/>
3rd Friday: Winterpalooza (Dec 18th)
<http://www.santacruzmah.org/event/winterpalooza-2/>

**Comment by halfempty** [comment]
@elisegranata okay, i think i fixed that issue

**Comment by elisegranata** [comment]
We have 4 people already! Awesome. However: I'm noticing that they have not
automatically been added to the Winterpalooza group in my MailChimp list.
When styling, did you by chance tweak the code?

For reference, here is the article on auto-adding new subscribers to
groups:
http://kb.mailchimp.com/lists/signup-forms/assign-subscribers-to-preselected-groups

On Tue, Dec 8, 2015 at 2:47 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> okay, i think i fixed
> that issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/51#issuecomment-163045639>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)


*Get to the MAH this month. Here's what's coming up:*
FREE First Friday: Wild Mushrooms & Functional Fungi Opening (Dec 4th)
<http://www.santacruzmah.org/event/free-first-friday-31/>
3rd Friday: Winterpalooza (Dec 18th)
<http://www.santacruzmah.org/event/winterpalooza-2/>

**Comment by elisegranata** [comment]
Hey Marty-- just sent out reminders to all who signed up here. Awesome! Can you update the button for Power Hour, the next 3rd Friday as soon as you get a chance? 

Thanks!

Elise

**Comment by halfempty** [comment]
@elisegranata Sorry I didn't jump on this quicker. You're wanting a reminder form for each of Power Hour and 3rd Friday?

**Comment by elisegranata** [comment]
For now, Power Hour is great. Eventually, all 3rd Fridays would be great.

On Wed, Dec 23, 2015 at 12:31 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @elisegranata <https://github.com/elisegranata> Sorry I didn't jump on
> this quicker. You're wanting a reminder form for each of Power Hour and 3rd
> Friday?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/51#issuecomment-166985340>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Okay, so, I made it something you can add to any event. On the right-hand side of the Edit Event screen, look for the Reminder Form box:

![image](https://cloud.githubusercontent.com/assets/775543/11985280/a9dd3dea-a988-11e5-9882-f1de8b47ee10.png)

Getting the Group ID and Integer from MailChimp is a bit tricky. Go to the Groups screen and open "View Groups":

![image](https://cloud.githubusercontent.com/assets/775543/11985302/ed86c430-a988-11e5-9b4f-b40f32be6126.png)

Click "Import to".  Then look at the URL string: 

![image](https://cloud.githubusercontent.com/assets/775543/11985317/11bf92f0-a989-11e5-8eaa-a28301391982.png)

"grp" is the group ID and "int" is the integer.

Make sense?

**Comment by elisegranata** [comment]
This is the best!!!!!!! Thank you so much, Marty. Brilliant workaround and
easy to do.

On Wed, Dec 23, 2015 at 1:24 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> Okay, so, I made it
> something you can add to any event. On the right-hand side of the Edit
> Event screen, look for the Reminder Form box:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/775543/11985280/a9dd3dea-a988-11e5-9882-f1de8b47ee10.png>
>
> Getting the Group ID and Integer from MailChimp is a bit tricky. Go to the
> Groups screen and open "View Groups":
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/775543/11985302/ed86c430-a988-11e5-9b4f-b40f32be6126.png>
>
> Click "Import to". Then look at the URL string:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/775543/11985317/11bf92f0-a989-11e5-8eaa-a28301391982.png>
>
> "grp" is the group ID and "int" is the integer.
>
> Make sense?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/51#issuecomment-166992167>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by elisegranata** [comment]
Hey Marty, is there any way to choose where we insert the "Reminders" block in an event description? I'm realizing for events where the description is long, like here (http://www.santacruzmah.org/event/lightning-talks-mysteries/), it might escape some visitors.
