### ISSUE TITLE
More prominent museum hours 

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#60]
@elisegranata, a fellow wrote in to say:

> "I had a hard time finding the hours that the museum is open."

To address it, I'm thinking we could make the Directions & Admissions strip, from the homepage, appear on all pages. Sound good?

**Comment by elisegranata** [comment]
I love it. Yes. Thank you. 

Elise Granata
@t: elisegranata
203.257.3525

Sent through the fabric of space and time via my iTelephone.

**Comment by halfempty** [comment]
@elisegranata I've added the "hours bar" to all pages. Please take a look here:

http://www.santacruzmah.org/events/

I wonder... In this context -- Events -- that it's unclear what the date means? Should it say something like "Today is Tuesday, February 9..." or something similar? To give context?

**Comment by elisegranata** [comment]
Yes, I love the "Today is..." tie in to make this ultra clear. Thank you.

On Tue, Feb 9, 2016 at 2:25 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> I've added the "hours
> bar" to all pages. Please take a look here:
>
> http://www.santacruzmah.org/events/
>
> I wonder... In this context -- Events -- that it's unclear what the date
> means? Should it say something like "Today is Tuesday, February 9..." or
> something similar? To give context?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/60#issuecomment-182106156>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Okay done!
