### ISSUE TITLE
Redirect needed - santacruzmah.org/volunteer

### ISSUE THREAD

**Issue by elisegranata** [santacruzmah/santacruzmah#61]
Can you redirect

http://www.santacruzmah.org/volunteer

to

http://www.santacruzmah.org/volunteer-opportunities/

**Comment by halfempty** [comment]
Done! It's actually really easy to make redirects. You can do it! Go Settings -> 301 Redirects.

**Comment by elisegranata** [comment]
Oh man, thank you Marty!

On Wed, Dec 23, 2015 at 12:28 PM, Marty Spellerberg <
notifications@github.com> wrote:

> Closed #61 <https://github.com/santacruzmah/santacruzmah/issues/61>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/61#event-499745301>.
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)
