### ISSUE TITLE
Add queued pictures to the persona images

### ISSUE THREAD

**Issue by elisegranata** [santacruzmah/santacruzmah#62]
As we are also changing the image of each persona with each activity, I also need to queue pictures for them. Is this possible?

**Comment by elisegranata** [comment]
Bumping this one. Would be a huge time save for me, and make the site's content more relevant overall.

**Comment by halfempty** [comment]
Done!

**Comment by elisegranata** [comment]
Thanks!

Elise Granata
@t: elisegranata
203.257.3525

Sent through the fabric of space and time via my iTelephone.
