### ISSUE TITLE
Remove Marcus from forms

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#64]
@elisegranata I know he's on "New submission from Make a donation to the MAH", 'cause I just received an autoresponse. He's probably on all the Join ones, and maybe some on the main site as well.

What address should replace his?

**Comment by elisegranata** [comment]
Good catch!

lis@santacruzmah.org can replace for the donations and the membership if
possible.

On Wed, Feb 17, 2016 at 3:52 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> I know he's on "New
> submission from Make a donation to the MAH", 'cause I just received an
> autoresponse. He's probably on all the Join ones, and maybe some on the
> main site as well.
>
> What address should replace his?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/64>.
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
Done
