### ISSUE TITLE
MuseumCamp Menu Change

### ISSUE THREAD

**Issue by elisegranata** [santacruzmah/santacruzmah#65]
Marty, can you create a divider on the MuseumCamp menu titled 'Past MuseumCamps' under 'Sponsor MuseumCamp'?

**Comment by halfempty** [comment]
@elisegranata Done! (may need to refresh cache to see)

**Comment by elisegranata** [comment]
Rad! Any way you can title it 'Past MuseumCamps'?

**Comment by halfempty** [comment]
@elisegranata Sure! How about that instead of a line? (see again)

**Comment by elisegranata** [comment]
If possible, I would prefer for this separator to be static. That page you
linked to isn't updated.

On Wed, Feb 24, 2016 at 5:25 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> Sure! How about that
> instead of a line? (see again)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/65#issuecomment-188547461>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Sure. Let's separate Past into its own menu, yes? It looks like there's already a menu created for Past MuseumCamps. Will you update that one to have the items you want? And I'll go ahead and add it to the site.

**Comment by halfempty** [comment]
@elisegranata Okay, that new menu is in. Update to your pleasure!

**Comment by elisegranata** [comment]
This is perfect. Thank you!!

On Thu, Feb 25, 2016 at 12:45 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @elisegranata <https://github.com/elisegranata> Okay, that new menu is
> in. Update to your pleasure!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/65#issuecomment-188977182>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by elisegranata** [comment]
Perfect. Thank you!

On Thu, Feb 25, 2016 at 12:45 PM, Marty Spellerberg <
notifications@github.com> wrote:

> @elisegranata <https://github.com/elisegranata> Okay, that new menu is
> in. Update to your pleasure!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/65#issuecomment-188977182>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)
