### ISSUE TITLE
Pull xml or html files from join.santacruzmah.org

### ISSUE THREAD

**Issue by elisegranata** [santacruzmah/santacruzmah#70]
Hi Marty,

We are interested in translating join.santacruzmah.org, and referred the translator to the main page-- he said that pulling text from this page is not best practice. See below.

> a.       Would it be possible to receive the files that were created within your team’s web development tool?  These would be html files, or perhaps xml files.  The reason is that pulling text from a web page online always is risky.  Inevitably, text is left out that needs to be translated, especially where there are links to other pages (e.g., clicking on the “Select” buttons for each membership level takes one to a different page).

We're trying for a quick turnaround on this. Is this something you can do quickly, or is it more of a pain? Let me know.

**Comment by halfempty** [comment]
@elisegranata Translation's back? Cool! 

The first thing I should say is that, overall, translation's not going to be something that's really a "quickie." There's a fairly large technology part to cover, and design as well. If it's a goal, it's something we should start discussing and planning for.

In terms of this particular request: The thing being requested doesn't really exist. WordPress assembles the pages from a number of different templates and records, many of which are forms. And don't forget the emails! 

But again, translating the existing text's not really how I would begin this kind of project. What's the scope of the translation that you've begun? The paper forms?

**Comment by elisegranata** [comment]
Ok-- we had just discussed changing over this single part of the site as a
landing page for spanish speakers, as we are not creating spanish print
collateral for membership yet. Can you elaborate on the type of planning
that would need to happen to move this forward?

Thank you!

On Fri, Mar 4, 2016 at 4:22 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> Translation's back? Cool!
>
> The first thing I should say is that, overall, translation's not going to
> be something that's really a "quickie." There's a fairly large technology
> part to cover, and design as well. If it's a goal, it's something we should
> start discussing and planning for.
>
> In terms of this particular request: The thing being requested doesn't
> really exist. WordPress assembles the pages from a number of different
> templates and records, many of which are forms. And don't forget the
> emails!
>
> But again, translating the existing text's not really how I would begin
> this kind of project. What's the scope of the translation that you've
> begun? The paper forms?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/70#issuecomment-192534123>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Are you and I meeting Tuesday?

**Comment by elisegranata** [comment]
Sorry- I thought Karen had e-mailed you about meeting with you instead this
Tuesday. I'm moving forward on CRM research but have not yet developed my
implementation plan for this spring and would like another week if possible.

Elise

On Fri, Mar 4, 2016 at 4:34 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> Are you and I meeting
> Tuesday?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/70#issuecomment-192536382>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata No problem. Just let me know when you'd like to meet to discuss this project.

**Comment by elisegranata** [comment]
Yes-- how about our usual time on March 15th?

On Fri, Mar 4, 2016 at 4:41 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> No problem. Just let me
> know when you'd like to meet to discuss this project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/70#issuecomment-192538469>
> .
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Works for me!
