### ISSUE TITLE
Membership: Update to match new brochure

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#74]

**Comment by halfempty** [comment]
@elisegranata Okay, I've done this. The new copy has unbalanced the layout a bit. Rather than try to fix it by tweaking the live site, I propose that we take a step back and do some mockups that also reflect the Stripe adjustments.

**Comment by elisegranata** [comment]
Sounds good to me. In the meantime, can you switch the Basic + Donor
levels? Also remove the descriptive text under 'Donor Levels' alltogether.

Elise

On Thu, Jun 9, 2016 at 2:15 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> Okay, I've done this. The
> new copy has unbalanced the layout a bit. Rather than try to fix it by
> tweaking the live site, I propose that we take a step back and do some
> mockups that also reflect the Stripe adjustments.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/74#issuecomment-225029057>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18uu-K36JsA-TaMjXPMppwM9XTHaspks5qKIJigaJpZM4H4ahe>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Done
