### ISSUE TITLE
Search bar white background

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#76]
![image](https://cloud.githubusercontent.com/assets/775543/14413804/02aa4fd8-ff3a-11e5-8b48-f4cc8532bc6f.png)

**Comment by halfempty** [comment]
Turns out it's a Safari bug-- you can't change the background color. So I've put in a hack and the text is now black in Safari.

**Comment by elisegranata** [comment]
Thank you Marty!

On Sun, Apr 10, 2016 at 4:50 PM, Marty Spellerberg <notifications@github.com
> wrote:

> Closed #76 <https://github.com/santacruzmah/santacruzmah/issues/76>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/76#event-621729137>
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)
