### ISSUE TITLE
Security / Malware response

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#78]
- [X] Order Security Audit from MT
$79 / once
https://ac.mediatemple.net/services/add/cloudtech/ondemand/start.mt?id=1481789

- [x] Order and configure WordFence Premium
$59 / annual
https://www.wordfence.com/wordfence-signup/ 

- [x] Move DNS from Cruzio to MT

- [x] Get SSL certificate from MT
$75 / annual
https://mediatemple.net/services/ssl/
https://mediatemple.net/community/products/dv/204643710/installing-an-ssl-certificate

- [ ] Move WordPress to HTTPS
https://css-tricks.com/moving-to-https-on-wordpress/

- [x] Upgrade Calendar plugin (flagged as vulnerability)

- [ ] MT recommendation: Update SSH port to something over 1000

- [x] MT recommendation: All directories should have 755 permissions and files should have 644 permissions (I think this is the big one)

**Comment by halfempty** [comment]
@elisegranata WordFence is unhappy that we haven't upgraded the calendar plugin and is flagging it as a vulnerability. I'll add that to the list, above.

**Comment by halfempty** [comment]
@elisegranata There were two actionable items in the MT scan. I've added them to the list above. I suspect the one about directory permissions is what's getting us

**Comment by elisegranata** [comment]
OK-- I have pretty limited knowledge around this and trust your recommendation. Let me know if I should share an urge for folks to change their passwords.

**Comment by halfempty** [comment]
@elisegranata I have updated WP + plugins on all the microsites. I've also installed the free version of WordFence on them, and run scans. Going to keep an eye on it...

**Comment by elisegranata** [comment]
Thank you Marty!

On Thu, Apr 28, 2016 at 9:43 AM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> I have updated WP +
> plugins on all the microsites. I've also installed the free version of
> WordFence on them, and run scans. Going to keep an eye on it...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/78#issuecomment-215490149>
>



-- 
Like what we do? Help us thrive – become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)
