### ISSUE TITLE
Sleeker point-of-donation

### ISSUE THREAD

**Issue by halfempty** [santacruzmah/santacruzmah#80]
**@elisegranata said:**

Hey Marty, Lis brought up the desire to change our POD (point-of-donation?! just made that up) system online to something that looks and flows better than PayPal-- hopefully with less cart abandonment, too.

This requires more discourse between us, but I am curious if you have any initial thoughts around Stripe, a sleeker PayPal plug-in...etc. We can chat on Tuesday at our usual time if you are available.

**Comment by elisegranata** [comment]
Elise will set up a Stripe account.
Marty will set up a test page.

**Comment by halfempty** [comment]
Good example of a form:
http://as220.org/donate/

**Comment by halfempty** [comment]
@elisegranata We have SSL on Join. Onward!

**Comment by elisegranata** [comment]
Yes! Thanks Marty.

On Thu, Jun 9, 2016 at 1:15 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> We have SSL on Join.
> Onward!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/80#issuecomment-225012899>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18uuF4iHgPuBP5tRNRxotTFxTQ0ZBNks5qKHRMgaJpZM4IWr1u>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata It should now be possible to test Stripe, from a technical / "what happens when we do X" perspective. So please have at it!

Our account is, I believe, in test mode. This is a setting both on the Stripe side and the WP side. If we find it useful to switch it to "live" to test, we can do that too.

From a user experience / design point of view, we'll need to make some adjustments, tho. I agree with the feedback you sent and will investigate how far we can take it from the default layout and look.

https://join.santacruzmah.org/new-individual-stripe/

**Comment by elisegranata** [comment]
Hey Marty-- we tried to test today but failed at testing!

This is a page that has test CC numbers <https://stripe.com/docs/testing>--
but we were not successful at this because they lack expiration dates and
CVC codes. Can you look into this please?

We'd prefer to test before trying it live to test if possible.

Elise

On Thu, Jun 9, 2016 at 2:00 PM, Marty Spellerberg <notifications@github.com>
wrote:

> @elisegranata <https://github.com/elisegranata> It should now be possible
> to test Stripe, from a technical / "what happens when we do X" perspective.
> So please have at it!
>
> Our account is, I believe, in test mode. This is a setting both on the
> Stripe side and the WP side. If we find it useful to switch it to "live" to
> test, we can do that too.
>
> From a user experience / design point of view, we'll need to make some
> adjustments, tho. I agree with the feedback you sent and will investigate
> how far we can take it from the default layout and look.
>
> https://join.santacruzmah.org/new-individual-stripe/
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/80#issuecomment-225025162>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18umZ88uCRzaadHYYjKbCLrsitjecaks5qKH8EgaJpZM4IWr1u>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata It looks like the MAH Stripe account is still in "test" mode. In this mode, transactions are not actually processed. It says:

>Before activating your account, you can only interact with Stripe in test mode. All of Stripe's features are available in test mode, though no live charges using the card networks can be created. 

https://stripe.com/docs/dashboard#activating-your-account

So I think you can try a regular card. I will now reduce the price of the test membership to $1, just in case.

**Comment by elisegranata** [comment]
Ok great, thank you! I will test with Lis tomorrow. Have you looked anymore
into the formatting of the Stripe form itself?

Elise

On Wed, Jun 15, 2016 at 1:46 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> It looks like the MAH
> Stripe account is still in "test" mode. In this mode, transactions are not
> actually processed. It says:
>
> Before activating your account, you can only interact with Stripe in test
> mode. All of Stripe's features are available in test mode, though no live
> charges using the card networks can be created.
>
> https://stripe.com/docs/dashboard#activating-your-account
>
> So I think you can try a regular card. I will now reduce the price of the
> test membership to $1, just in case.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/80#issuecomment-226314870>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18uspIqCvP4LNKnlzAfIjB6PAjuvjYks5qMGS1gaJpZM4IWr1u>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by elisegranata** [comment]
Ok! Lis and I activated the account, but then saw this notification. Do you
need to do anything on your end before we test with my CC?

Elise

On Thu, Jun 16, 2016 at 3:27 PM, Elise Granata <elise@santacruzmah.org>
wrote:

> Ok great, thank you! I will test with Lis tomorrow. Have you looked
> anymore into the formatting of the Stripe form itself?
>
> Elise
>
> On Wed, Jun 15, 2016 at 1:46 PM, Marty Spellerberg <
> notifications@github.com> wrote:
>
>> @elisegranata <https://github.com/elisegranata> It looks like the MAH
>> Stripe account is still in "test" mode. In this mode, transactions are not
>> actually processed. It says:
>>
>> Before activating your account, you can only interact with Stripe in test
>> mode. All of Stripe's features are available in test mode, though no live
>> charges using the card networks can be created.
>>
>> https://stripe.com/docs/dashboard#activating-your-account
>>
>> So I think you can try a regular card. I will now reduce the price of the
>> test membership to $1, just in case.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/santacruzmah/santacruzmah/issues/80#issuecomment-226314870>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AF18uspIqCvP4LNKnlzAfIjB6PAjuvjYks5qMGS1gaJpZM4IWr1u>
>> .
>>
>
>
>
> --
> The best way to support the museum. Become a MAH member today
> <http://join.santacruzmah.org/>.
>
> *Elise Granata*
> *Marketing & Engagement Coordinator*
> *Santa Cruz Museum of Art & History*
> *705 Front Street | Santa Cruz | CA 95060*
>
> *831.429.1964 ext 7028 <831.429.1964%20ext%207028>*
> Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
> <http://www.facebook.com/santacruzmah>.
>
> *Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
> change on event days)
>
>
>
>
>
>


-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata Not sure I follow? It's out of test-mode now? Can you put it back in test mode? On the website side we're still in test mode. (Not sure what the effect of that is, tho.) 

The test product is $1, just in case it does go through.

https://join.santacruzmah.org/new-individual-stripe/

I began some experimenting with the style. I've removed the default style, so you'll notice the test page looks really raw.

And then I've moved the CC fields to a second page, which you should see when you click "Next."

I have an idea for how I'd like the process to be, though I'm still experimenting to see what's possible.

**Comment by elisegranata** [comment]
Sounds good. I just wanted to check with you to see if the things that
screenshot says to 'double check' are double checked?

On Fri, Jun 17, 2016 at 3:12 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> Not sure I follow? It's
> out of test-mode now? Can you put it back in test mode? On the website side
> we're still in test mode. (Not sure what the effect of that is, tho.)
>
> The test product is $1, just in case it does go through.
>
> https://join.santacruzmah.org/new-individual-stripe/
>
> I began some experimenting with the style. I've removed the default style,
> so you'll notice the test page looks really raw.
>
> And then I've moved the CC fields to a second page, which you should see
> when you click "Next."
>
> I have an idea for how I'd like the process to be, though I'm still
> experimenting to see what's possible.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/80#issuecomment-226893830>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18ugOcebWUr5YLh08lIA3HF7j1uIGWks5qMxvYgaJpZM4IWr1u>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by elisegranata** [comment]
Can you confirm we are good to go? If so, I will move forward with testing.

Elise

On Fri, Jun 17, 2016 at 4:26 PM, Elise Granata <elise@santacruzmah.org>
wrote:

> Sounds good. I just wanted to check with you to see if the things that
> screenshot says to 'double check' are double checked?
>
> On Fri, Jun 17, 2016 at 3:12 PM, Marty Spellerberg <
> notifications@github.com> wrote:
>
>> @elisegranata <https://github.com/elisegranata> Not sure I follow? It's
>> out of test-mode now? Can you put it back in test mode? On the website side
>> we're still in test mode. (Not sure what the effect of that is, tho.)
>>
>> The test product is $1, just in case it does go through.
>>
>> https://join.santacruzmah.org/new-individual-stripe/
>>
>> I began some experimenting with the style. I've removed the default
>> style, so you'll notice the test page looks really raw.
>>
>> And then I've moved the CC fields to a second page, which you should see
>> when you click "Next."
>>
>> I have an idea for how I'd like the process to be, though I'm still
>> experimenting to see what's possible.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/santacruzmah/santacruzmah/issues/80#issuecomment-226893830>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AF18ugOcebWUr5YLh08lIA3HF7j1uIGWks5qMxvYgaJpZM4IWr1u>
>> .
>>
>
>
>
> --
> The best way to support the museum. Become a MAH member today
> <http://join.santacruzmah.org/>.
>
> *Elise Granata*
> *Marketing & Engagement Coordinator*
> *Santa Cruz Museum of Art & History*
> *705 Front Street | Santa Cruz | CA 95060*
>
> *831.429.1964 ext 7028 <831.429.1964%20ext%207028>*
> Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
> <http://www.facebook.com/santacruzmah>.
>
> *Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
> change on event days)
>
>
>
>
>
>


-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)
