### ISSUE TITLE
MailChimp - Custom Domain Authentication

### ISSUE THREAD

**Issue by elisegranata** [santacruzmah/santacruzmah#83]
Hey Marty, as far as I know from the monkey help person that I just chatted with at MailChimp, this could potentially have HUGE positive impact on our delivery and open rate. Our e-mails have either been landing in Spam/Promotions tab in Gmail folks' inboxes, or never ending up there at all! Would you mind looking into this as soon as you have a chance, please?

http://kb.mailchimp.com/accounts/email-authentication/set-up-custom-domain-authentication-dkim-and-spf?utm_source=mc-kb&utm_medium=kb-site&utm_campaign=eepurl

**Comment by halfempty** [comment]
@elisegranata Okay, this is done!

**Comment by elisegranata** [comment]
Wow yay, fast and amazing! Thank you Marty.


On Fri, Jun 10, 2016 at 1:09 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> Okay, this is done!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/83#issuecomment-225283092>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18uoTHQxs58wNa5fFz2dTRFPKAQ1BQks5qKcRqgaJpZM4IzICV>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by elisegranata** [comment]
I know the article said there may be a 72 hour waiting period before the
change takes effect...will we be notified when this happens?

On Fri, Jun 10, 2016 at 1:19 PM, Elise Granata <elise@santacruzmah.org>
wrote:

> Wow yay, fast and amazing! Thank you Marty.
>
>
> On Fri, Jun 10, 2016 at 1:09 PM, Marty Spellerberg <
> notifications@github.com> wrote:
>
>> @elisegranata <https://github.com/elisegranata> Okay, this is done!
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/santacruzmah/santacruzmah/issues/83#issuecomment-225283092>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AF18uoTHQxs58wNa5fFz2dTRFPKAQ1BQks5qKcRqgaJpZM4IzICV>
>> .
>>
>
>
>
> --
> The best way to support the museum. Become a MAH member today
> <http://join.santacruzmah.org/>.
>
> *Elise Granata*
> *Marketing & Engagement Coordinator*
> *Santa Cruz Museum of Art & History*
> *705 Front Street | Santa Cruz | CA 95060*
>
> *831.429.1964 ext 7028 <831.429.1964%20ext%207028>*
> Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
> <http://www.facebook.com/santacruzmah>.
>
> *Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
> change on event days)
>
>
>
>
>
>


-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)

**Comment by halfempty** [comment]
@elisegranata It was quick, and accepted the change right away. It’s complete.

**Comment by elisegranata** [comment]
Wunderbar! Thank you.

On Fri, Jun 10, 2016 at 1:31 PM, Marty Spellerberg <notifications@github.com
> wrote:

> @elisegranata <https://github.com/elisegranata> It was quick, and
> accepted the change right away. It’s complete.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/santacruzmah/santacruzmah/issues/83#issuecomment-225287910>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF18uspTGMwoUa7g0_M6sl333uKDbKyRks5qKcmagaJpZM4IzICV>
> .
>



-- 
The best way to support the museum. Become a MAH member today
<http://join.santacruzmah.org/>.

*Elise Granata*
*Marketing & Engagement Coordinator*
*Santa Cruz Museum of Art & History*
*705 Front Street | Santa Cruz | CA 95060*

*831.429.1964 ext 7028*
Visit our website <http://www.santacruzmah.org/>* or* join our Facebook
<http://www.facebook.com/santacruzmah>.

*Wanna know my hours? You're in luck:Monday-Friday *9AM-5PM (subject to
change on event days)
